// id, week, year, authors, English title, Chinese title, URL, link label, alternative source
window.UME_READINGS = [
["M04",1,1992,"Gary S. Becker","The Economic Way of Looking at Life","观察生活的经济学方式","https://www.nobelprize.org/uploads/2018/06/becker-lecture.pdf","PDF","https://www.nobelprize.org/prizes/economic-sciences/1992/becker/lecture/"],
["M01",1,1945,"F. A. Hayek","The Use of Knowledge in Society","知识在社会中的运用","https://home.uchicago.edu/~vlima/courses/econ200/spring01/hayek.pdf","PDF",""],
["C02",1,1974,"F. A. Hayek","The Pretence of Knowledge","知识的僭妄","https://www.nobelprize.org/prizes/economic-sciences/1974/hayek/lecture/","原文页",""],
["M02",2,1953,"Milton Friedman","The Methodology of Positive Economics","实证经济学的方法论","https://web.stanford.edu/~avner/Greif_228_2005/Friedman%201953%20Methodology.pdf","PDF",""],
["M03",2,1978,"Herbert A. Simon","Rational Decision-Making in Business Organizations","企业组织中的理性决策","https://www.nobelprize.org/uploads/2018/06/simon-lecture.pdf","PDF","https://www.nobelprize.org/prizes/economic-sciences/1978/simon/lecture/"],
["M09",3,1951,"John Nash","Non-Cooperative Games","非合作博弈","https://www.cs.upc.edu/~ia/nash51.pdf","PDF",""],
["M16",3,1962,"David Gale and Lloyd S. Shapley","College Admissions and the Stability of Marriage","大学录取与婚姻的稳定性","https://www.math.utoronto.ca/mccann/assignments/477/GaleShapley62.pdf","PDF",""],
["M13",3,1950,"Kenneth J. Arrow","A Difficulty in the Concept of Social Welfare","社会福利概念中的一个困难","https://www.journals.uchicago.edu/doi/10.1086/256963","原文页",""],
["M17",4,1970,"George A. Akerlof","The Market for “Lemons”: Quality Uncertainty and the Market Mechanism","“柠檬”市场","https://econweb.ucsd.edu/~atimmerm/174/akerlof.pdf","PDF",""],
["C17",4,2000,"Daniel L. McFadden","Economic Choices","经济选择","https://www.nobelprize.org/uploads/2018/06/mcfadden-lecture.pdf","PDF","https://www.nobelprize.org/prizes/economic-sciences/2000/mcfadden/lecture/"],
["M05",5,1937,"John Maynard Keynes","The General Theory of Employment","就业的一般理论","https://www.hetwebsite.net/het/texts/keynes/keynes1937qje.pdf","PDF","https://academic.oup.com/qje/article-abstract/51/2/209/1939387"],
["C06",5,1968,"Gary S. Becker","Crime and Punishment: An Economic Approach","犯罪与惩罚：一种经济学分析","https://laws21.classes.ryansafner.com/readings/Becker-1968.pdf","PDF",""],
["M07",6,1937,"R. H. Coase","The Nature of the Firm","企业的性质","https://faculty.washington.edu/mfan/is582/articles/Coase1937.pdf","PDF","https://onlinelibrary.wiley.com/doi/10.1111/j.1468-0335.1937.tb00002.x"],
["M10",6,1954,"Kenneth J. Arrow and Gerard Debreu","Existence of an Equilibrium for a Competitive Economy","竞争经济的均衡存在性","https://www.math.uchicago.edu/~shmuel/AAT-readings/Econ%20segment/Arrow-DeBreu.pdf","PDF",""],
["M38",7,1994,"Guido W. Imbens and Joshua D. Angrist","Identification and Estimation of Local Average Treatment Effects","局部平均处理效应的识别与估计","https://eclass.uoa.gr/modules/document/file.php/ECON261/Randomized%20evaluation%20papers/Imbens%20%26%20Angrist%20-%20LATE.pdf","PDF","https://www.jstor.org/stable/2951620"],
["M37",7,2000,"James J. Heckman","Microdata, Heterogeneity and the Evaluation of Public Policy","微观数据、异质性与公共政策评价","https://www.nobelprize.org/uploads/2018/06/heckman-lecture.pdf","PDF","https://www.nobelprize.org/prizes/economic-sciences/2000/heckman/lecture/"],
["C01",8,1955,"Herbert A. Simon","A Behavioral Model of Rational Choice","理性选择的行为模型","https://iiif.library.cmu.edu/file/Simon_box00063_fld04838_bdl0001_doc0001/Simon_box00063_fld04838_bdl0001_doc0001.pdf","PDF",""],
["M06",8,1979,"Daniel Kahneman and Amos Tversky","Prospect Theory: An Analysis of Decision under Risk","前景理论","https://kahneman.scholar.princeton.edu/document/11","PDF",""],
["M11",9,1971,"Thomas C. Schelling","Dynamic Models of Segregation","隔离的动态模型","https://www.dpi.inpe.br/gilberto/cursos/cst-317/papers/schelling_segregation.pdf","PDF",""],
["M20",9,1979,"Bengt Holmström","Moral Hazard and Observability","道德风险与可观测性","https://people.duke.edu/~qc2/BA532/1979%20Rand%20Holmstrom.pdf","PDF",""],
["M28",10,1956,"Robert M. Solow","A Contribution to the Theory of Economic Growth","经济增长理论的一项贡献","https://cooperative-individualism.org/solow-robert_a-contribution-to-the-theory-of-economic-growth-1956-feb.pdf","PDF","https://academic.oup.com/qje/article-abstract/70/1/65/1903777"],
["C11",10,1986,"Paul M. Romer","Increasing Returns and Long-Run Growth","收益递增与长期增长","https://www.dklevine.com/archive/refs42232.pdf","PDF",""],
["M18",11,1963,"Kenneth J. Arrow","Uncertainty and the Welfare Economics of Medical Care","不确定性与医疗保健的福利经济学","https://www.aeaweb.org/aer/top20/53.5.941-973.pdf","PDF",""],
["M19",11,1973,"Michael Spence","Job Market Signaling","劳动力市场信号","https://www.sfu.ca/~allen/Spence.pdf","PDF","https://academic.oup.com/qje/article-abstract/87/3/355/1909092"],
["M08",12,1960,"R. H. Coase","The Problem of Social Cost","社会成本问题","https://bev.berkeley.edu/ipe/readings/The%20Problem%20of%20Social%20Cost.pdf","PDF",""],
["M21",12,1986,"Sanford J. Grossman and Oliver D. Hart","The Costs and Benefits of Ownership: A Theory of Vertical and Lateral Integration","所有权的成本与收益","https://faculty.washington.edu/mfan/is582/articles/GH1986.pdf","PDF","https://www.journals.uchicago.edu/doi/abs/10.1086/261404"],
["M12",13,1954,"Paul A. Samuelson","The Pure Theory of Public Expenditure","公共支出的纯理论","https://courses.cit.cornell.edu/econ335/out/samuelson_pure.pdf","PDF",""],
["C07",13,1956,"Charles M. Tiebout","A Pure Theory of Local Expenditures","地方支出的纯理论","https://courses.cit.cornell.edu/econ4260/out%20combined/Tiebout-PureTheoryLocal-1956.pdf","PDF",""],
["M15",13,2009,"Elinor Ostrom","Beyond Markets and States: Polycentric Governance of Complex Economic Systems","超越市场与国家","https://www.nobelprize.org/uploads/2018/06/ostrom_lecture.pdf","PDF","https://www.nobelprize.org/prizes/economic-sciences/2009/ostrom/lecture/"],
["C09",14,1977,"Avinash K. Dixit and Joseph E. Stiglitz","Monopolistic Competition and Optimum Product Diversity","垄断竞争与最优产品多样性","https://www.aeaweb.org/aer/top20/67.3.297-308.pdf","PDF",""],
["M29",14,1990,"Paul M. Romer","Endogenous Technological Change","内生技术变迁","https://web.stanford.edu/~klenow/Romer_1990.pdf","PDF",""],
["M30",15,1976,"Robert E. Lucas, Jr.","Econometric Policy Evaluation: A Critique","计量经济政策评价：一个批判","https://www.dpipe.tsukuba.ac.jp/~naito/teaching_web/public_economics_2013_web/Lucas_critieque_1983.pdf","PDF",""],
["M31",15,1977,"Finn E. Kydland and Edward C. Prescott","Rules Rather than Discretion: The Inconsistency of Optimal Plans","规则优于相机抉择：最优计划的不一致性","https://drphilipshaw.com/Protected/Rules%20Rather%20than%20Discretion-The%20Inconsistency%20of%20Optimal%20Plans.pdf","PDF","https://www.journals.uchicago.edu/doi/abs/10.1086/260580"],
["C05",16,1961,"George J. Stigler","The Economics of Information","信息经济学","https://home.uchicago.edu/~vlima/courses/econ200/spring01/stigler.pdf","PDF",""],
["M40",16,1987,"John Rust","Optimal Replacement of GMC Bus Engines: An Empirical Model of Harold Zurcher","GMC巴士发动机的最优更换","https://www.its.caltech.edu/~mshum/stats/rust.pdf","PDF",""],
["C08",17,1961,"William Vickrey","Counterspeculation, Auctions, and Competitive Sealed Tenders","反投机、拍卖与竞争性密封投标","https://www.cs.princeton.edu/courses/archive/spr09/cos444/papers/vickrey61.pdf","PDF",""],
["M26",17,1981,"Roger B. Myerson","Optimal Auction Design","最优拍卖设计","https://www.math.utoronto.ca/mccann/assignments/477/Myerson81.pdf","PDF","https://pubsonline.informs.org/doi/10.1287/moor.6.1.58"],
["M25",18,1971,"James A. Mirrlees","An Exploration in the Theory of Optimum Income Taxation","最优所得税理论探索","https://www.uib.cat/depart/deaweb/webpersonal/amedeospadaro/workingpapers/bibliosecpub/MirrleesRES1971.pdf","PDF","https://academic.oup.com/restud/article-abstract/38/2/175/1527903"],
["C13",18,2001,"Emmanuel Saez","Using Elasticities to Derive Optimal Income Tax Rates","利用弹性推导最优所得税率","https://eml.berkeley.edu/~saez/derive.pdf","PDF",""],
["M22",19,1982,"Vincent P. Crawford and Joel Sobel","Strategic Information Transmission","战略性信息传递","https://www.edegan.com/pdfs/Crawford%20Sobel%20%281982%29%20-%20Strategic%20Information%20Transmission.pdf","PDF",""],
["M24",19,2011,"Emir Kamenica and Matthew Gentzkow","Bayesian Persuasion","贝叶斯说服","https://web.stanford.edu/~gentzkow/research/BayesianPersuasion.pdf","PDF",""],
["C15",20,1970,"Eugene F. Fama","Efficient Capital Markets: A Review of Theory and Empirical Work","有效资本市场","https://people.hec.edu/rosu/wp-content/uploads/sites/43/2023/09/Fama-Efficient-capital-markets-1970.pdf","PDF",""],
["M23",20,1980,"Sanford J. Grossman and Joseph E. Stiglitz","On the Impossibility of Informationally Efficient Markets","信息有效市场的不可能性","https://www.aeaweb.org/aer/top20/70.3.393-408.pdf","PDF",""],
["C10",21,1980,"Paul R. Krugman","Scale Economies, Product Differentiation, and the Pattern of Trade","规模经济、产品差异化与贸易格局","https://www.aeaweb.org/aer/top20/70.5.950-959.pdf","PDF",""],
["C03",21,2001,"Joseph E. Stiglitz","Information and the Change in the Paradigm in Economics","信息与经济学范式的变迁","https://www.nobelprize.org/uploads/2018/06/stiglitz-lecture.pdf","PDF","https://www.nobelprize.org/prizes/economic-sciences/2001/stiglitz/lecture/"],
["M34",22,2003,"Marc J. Melitz","The Impact of Trade on Intra-Industry Reallocations and Aggregate Industry Productivity","贸易、产业内再配置与行业生产率","https://users.econ.umn.edu/~tkehoe/papers/Melitz.pdf","PDF","https://melitz.scholars.harvard.edu/publications/impact-trade-intra-industry-reallocations-and-aggregate-industry-productivity"],
["M14",22,1998,"Amartya Sen","The Possibility of Social Choice","社会选择的可能性","https://www.nobelprize.org/prizes/economic-sciences/1998/sen/lecture/","原文页",""],
["C04",23,1938,"Paul A. Samuelson","A Note on the Pure Theory of Consumer’s Behaviour","消费者行为纯理论札记","https://www.jstor.org/stable/2548836","原文页",""],
["M41",23,1995,"Steven Berry, James Levinsohn and Ariel Pakes","Automobile Prices in Market Equilibrium","市场均衡中的汽车价格","https://www.jstor.org/stable/2171802","原文页",""],
["C14",24,2009,"Chang-Tai Hsieh and Peter J. Klenow","Misallocation and Manufacturing TFP in China and India","中国与印度制造业的错配与全要素生产率","https://klenow.com/MMTFP.pdf","PDF",""],
["C16",24,1981,"Robert J. Shiller","Do Stock Prices Move Too Much to Be Justified by Subsequent Changes in Dividends?","股票价格是否过度波动？","https://www.aeaweb.org/aer/top20/71.3.421-436.pdf","PDF",""],
["M42",25,2013,"David H. Autor, David Dorn and Gordon H. Hanson","The China Syndrome: Local Labor Market Effects of Import Competition in the United States","中国综合征","https://economics.mit.edu/sites/default/files/publications/the%20china%20syndrome%202013.pdf","PDF",""],
["M39",25,2009,"Raj Chetty","Sufficient Statistics for Welfare Analysis: A Bridge Between Structural and Reduced-Form Methods","福利分析的充分统计量","https://dash.harvard.edu/entities/publication/73120378-a796-6bd4-e053-0100007fdf3b","原文页",""],
["M32",26,1958,"Franco Modigliani and Merton H. Miller","The Cost of Capital, Corporation Finance and the Theory of Investment","资本成本、公司融资与投资理论","https://eaesp.fgv.br/sites/default/files/legacy/pesquisa-eaesp-files/arquivos/terra_-_the_cost_of_capital_corporation_finance.pdf","PDF",""],
["M33",26,1983,"Douglas W. Diamond and Philip H. Dybvig","Bank Runs, Deposit Insurance, and Liquidity","银行挤兑、存款保险与流动性","https://www.minneapolisfed.org/research/quarterly-review/bank-runs-deposit-insurance-and-liquidity","原文页",""],
["C12",27,1968,"Milton Friedman","The Role of Monetary Policy","货币政策的作用","https://www.aeaweb.org/aer/top20/58.1.1-17.pdf","PDF",""],
["M35",27,2018,"Greg Kaplan, Benjamin Moll and Giovanni L. Violante","Monetary Policy According to HANK","HANK框架下的货币政策","https://benjaminmoll.com/wp-content/uploads/2019/07/HANK.pdf","PDF",""],
["M27",28,1974,"Martin L. Weitzman","Prices vs. Quantities","价格与数量","https://www.sfu.ca/~wainwrig/Econ400/documents/weitzman-pricevsquantities-Rev-Econ_Stud.pdf","PDF","https://academic.oup.com/restud/article-abstract/41/4/477/1543334"],
["M36",28,2020,"David Rezza Baqaee and Emmanuel Farhi","Productivity and Misallocation in General Equilibrium","一般均衡中的生产率与错配","https://academic.oup.com/qje/article/135/1/105/5573281","原文页",""]
];
